services:
  zentitle-lls-db:
    image: postgres:18.4
    restart: always
    container_name: zentitle-lls-db
    environment:
      POSTGRES_DB: "lls"
      POSTGRES_USER: "lls-admin"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "lls", "-U", "lls-admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=250'
    ports:
      - "5433:5432"

  zentitle-lls:
    image: registry.gitlab.com/nalpeiron/zentitle/local-license-server:2.3.0
    restart: always
    container_name: zentitle-lls
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:6501"
      ConnectionStrings__Database: "Server=zentitle-lls-db; Database=lls; User Id=lls-admin; Password=password; Maximum Pool Size=128; Minimum Pool Size=32; Timeout=5; Command Timeout=15; Keepalive=30"
      Authentication__Username: "admin"
      Authentication__Password: "admin"
      LoggingLevel__MinimumLevel: "Warning"
      LlsLogs__Enabled: true
      LlsLogs__RetentionDays: 14
    ports:
      - "6501:6501"
    depends_on:
      zentitle-lls-db:
        condition: service_healthy
