#!/usr/bin/env node

"use strict";

const http = require("http");
const https = require("https");
const readline = require("readline");
const fs = require("fs");

const pipedAnswers = process.stdin.isTTY
  ? null
  : fs.readFileSync(0, "utf8").split(/\r?\n/);

const ENV_FILE_PATH = `${__dirname}/lls_activation_walkthrough.env`;
const storedEnv = readEnvFile(ENV_FILE_PATH);
const envUpdates = {};
const ENV_KEYS = {
  managementApiUrl: "MANAGEMENT_API_URL",
  managementTokenUrl: "MANAGEMENT_TOKEN_URL",
  tenantId: "TENANT_ID",
  managementClientId: "MANAGEMENT_CLIENT_ID",
  llsUrl: "LLS_URL",
  llsUsername: "LLS_USERNAME",
  llsServerName: "LLS_SERVER_NAME",
  entitlementId: "ENTITLEMENT_ID",
};

let rl = null;
let originalWriteToOutput = null;
let muteReadlineOutput = false;

class ApiError extends Error {
  constructor(method, url, statusCode, body) {
    super(`${method} ${url} failed with HTTP ${statusCode}`);
    this.method = method;
    this.url = url;
    this.statusCode = statusCode;
    this.body = body;
  }
}

async function main() {
  console.log("Local License Server setup");
  console.log();
  console.log("This wizard activates your Local License Server and imports your first entitlement.");
  console.log("Have your Zentitle2 Management API credentials, LLS credentials, activation code,");
  console.log("and entitlement ID ready.");
  console.log(`Previous non-secret values are loaded from ${ENV_FILE_PATH} when present.`);
  console.log();

  const managementApiUrl = trimTrailingSlash(
    await promptStoredRequired("Zentitle2 Management API URL", ENV_KEYS.managementApiUrl)
  );
  envUpdates[ENV_KEYS.managementApiUrl] = managementApiUrl;

  const managementTokenUrl = normalizeTokenUrl(
    await promptStoredRequired(
      "Identity provider URL from API credentials page or full token URL",
      ENV_KEYS.managementTokenUrl
    )
  );
  envUpdates[ENV_KEYS.managementTokenUrl] = managementTokenUrl;

  const tenantId = await promptStoredRequired("Tenant ID", ENV_KEYS.tenantId);
  envUpdates[ENV_KEYS.tenantId] = tenantId;

  const managementClientId = await promptStoredRequired(
    "Management API client ID",
    ENV_KEYS.managementClientId
  );
  envUpdates[ENV_KEYS.managementClientId] = managementClientId;

  const managementClientSecret = await promptSecretRequired("Management API client secret");

  const llsUrl = trimTrailingSlash(await promptStoredRequired("LLS URL", ENV_KEYS.llsUrl));
  envUpdates[ENV_KEYS.llsUrl] = llsUrl;
  const llsRequestOptions = {
    allowSelfSignedCertificate: isHttpsUrl(llsUrl),
  };
  if (llsRequestOptions.allowSelfSignedCertificate) {
    console.log("Self-signed TLS certificates will be accepted for LLS requests.");
  }

  const llsUsername = await promptStoredRequired("LLS username", ENV_KEYS.llsUsername);
  envUpdates[ENV_KEYS.llsUsername] = llsUsername;

  const llsPassword = await promptSecretRequired("LLS password");

  writeEnvFile(ENV_FILE_PATH, envUpdates);
  console.log(`Saved non-secret values to ${ENV_FILE_PATH}.`);

  console.log();
  console.log("Requesting Management API access token...");
  const managementToken = await getManagementToken({
    managementTokenUrl,
    managementClientId,
    managementClientSecret,
  });

  const llsAuthHeaders = {
    Authorization: `Basic ${Buffer.from(`${llsUsername}:${llsPassword}`, "utf8").toString("base64")}`,
    "N-TenantId": tenantId,
  };

  const managementAuthHeaders = {
    Authorization: managementToken,
    "N-TenantId": tenantId,
  };

  console.log();
  console.log("Connecting to LLS...");
  const llsServer = await getJson(
    `${llsUrl}/api/v1/lls/server`,
    llsAuthHeaders,
    llsRequestOptions
  );
  const llsServerId = llsServer.id || "<unknown id>";
  console.log(`Connected to LLS server: ${llsServerId}`);

  console.log();
  console.log("Checking LLS license status...");
  const llsLicenseStatus = await getJson(
    `${llsUrl}/api/v1/lls/license/status`,
    llsAuthHeaders,
    llsRequestOptions
  );
  const status = llsLicenseStatus.status || "<unknown>";

  if (status === "active") {
    const seatName = llsLicenseStatus.seatName || "<unknown>";
    console.log(`LLS license is already active: status=${status}, seatName=${seatName}`);
  } else {
    console.log(`LLS license status: ${status}`);
    console.log();

    const activationCode = await promptRequired("LLS activation code");
    const serverName = await promptStoredRequired("LLS server name", ENV_KEYS.llsServerName);
    envUpdates[ENV_KEYS.llsServerName] = serverName;

    console.log();
    console.log("Generating activation token in LLS...");
    const activationTokenResponse = await postJson(
      `${llsUrl}/api/v1/lls/license/generate-activation-token`,
      { activationCode, serverName },
      llsAuthHeaders,
      llsRequestOptions
    );
    const activationToken = requireToken(activationTokenResponse, "LLS activation token response");

    console.log();
    console.log("Activation token generated by LLS:");
    console.log(maskToken(activationToken));

    console.log();
    console.log("Activating your LLS seat in Zentitle2...");
    const activationResponse = await postJson(
      `${managementApiUrl}/api/v1/local-license-servers/license/activate`,
      { token: activationToken },
      managementAuthHeaders
    );
    const activationResponseToken = requireToken(
      activationResponse,
      "Management API activation response"
    );

    console.log();
    console.log("Activation response token generated by Zentitle2:");
    console.log(maskToken(activationResponseToken));

    console.log();
    console.log("Applying activation response token to LLS...");
    const llsActivationResponse = await postJson(
      `${llsUrl}/api/v1/lls/license/activate`,
      { token: activationResponseToken },
      llsAuthHeaders,
      llsRequestOptions
    );
    const activatedStatus = llsActivationResponse.status || "<unknown>";
    const activatedSeatName = llsActivationResponse.seatName || "<unknown>";

    console.log();
    console.log(`LLS license activated: status=${activatedStatus}, seatName=${activatedSeatName}`);
  }

  console.log();
  const entitlementId = await promptStoredRequired("Entitlement ID", ENV_KEYS.entitlementId);
  envUpdates[ENV_KEYS.entitlementId] = entitlementId;
  const entitlementIdPath = encodeURIComponent(entitlementId);

  console.log();
  console.log("Exporting entitlement to LLS in Zentitle2...");
  const entitlementExportResponse = await postJson(
    `${managementApiUrl}/api/v1/entitlements/${entitlementIdPath}/export`,
    { localLicenseServerId: llsServerId },
    managementAuthHeaders
  );
  const entitlementImportToken = requireToken(
    entitlementExportResponse,
    "Management API entitlement export response"
  );

  console.log("Entitlement import token generated:");
  console.log(maskToken(entitlementImportToken));

  console.log();
  console.log("Importing entitlement into LLS...");
  const importedEntitlement = await postJson(
    `${llsUrl}/api/v1/lls/entitlements/import`,
    { token: entitlementImportToken },
    llsAuthHeaders,
    llsRequestOptions
  );

  printEntitlementSummary(importedEntitlement);

  console.log();
  console.log("LLS setup complete.");
  closeReadline();
}

async function getManagementToken(config) {
  const form = new URLSearchParams({
    grant_type: "client_credentials",
    client_id: config.managementClientId,
    client_secret: config.managementClientSecret,
  }).toString();

  let response;
  try {
    response = await requestJson("POST", config.managementTokenUrl, {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: form,
    });
  } catch (error) {
    if (error instanceof ApiError) {
      console.error(`HTTP ${error.statusCode} while requesting a Management API access token`);
      console.error(`Token URL: ${config.managementTokenUrl}`);
      if (error.body) {
        console.error(error.body);
      }

      const parsed = parseJson(error.body);
      if (parsed && parsed.error === "invalid_client") {
        console.error("The client ID/secret were not accepted by this identity provider realm.");
      } else if (parsed && parsed.error === "Realm does not exist") {
        console.error("The identity provider URL points to a realm that does not exist.");
      }

      console.error("Use the identity provider URL shown with the same API credential in Zentitle2.");
    }

    throw error;
  }

  if (!response.access_token) {
    throw new Error("Token response did not include access_token.");
  }

  return `Bearer ${response.access_token}`;
}

function getJson(url, headers, requestOptions = {}) {
  return requestJson("GET", url, { headers, ...requestOptions });
}

function postJson(url, body, headers, requestOptions = {}) {
  return requestJson("POST", url, {
    headers: {
      ...headers,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
    ...requestOptions,
  });
}

function requestJson(method, url, options = {}) {
  return new Promise((resolve, reject) => {
    const parsedUrl = new URL(url);
    const transport = parsedUrl.protocol === "http:" ? http : https;
    const body = options.body ? Buffer.from(options.body, "utf8") : null;

    const request = transport.request(
      parsedUrl,
      {
        method,
        rejectUnauthorized: options.allowSelfSignedCertificate ? false : undefined,
        headers: {
          Accept: "application/json",
          ...(options.headers || {}),
          ...(body ? { "Content-Length": body.length } : {}),
        },
      },
      (response) => {
        const chunks = [];
        response.on("data", (chunk) => chunks.push(chunk));
        response.on("end", () => {
          const responseBody = Buffer.concat(chunks).toString("utf8");

          if (response.statusCode < 200 || response.statusCode > 299) {
            reject(new ApiError(method, url, response.statusCode, responseBody));
            return;
          }

          if (!responseBody) {
            resolve({});
            return;
          }

          const parsedBody = parseJson(responseBody);
          if (!parsedBody) {
            reject(new Error(`${method} ${url} did not return JSON: ${responseBody}`));
            return;
          }

          resolve(parsedBody);
        });
      }
    );

    request.on("error", reject);
    request.setTimeout(60000, () => {
      request.destroy(new Error(`${method} ${url} timed out.`));
    });

    if (body) {
      request.write(body);
    }

    request.end();
  });
}

function printEntitlementSummary(entitlement) {
  const product = entitlement.product || {};
  const group = entitlement.group || {};
  const activationCodes = group.activationCodes || entitlement.activationCodes || [];
  const features = entitlement.features || [];
  const attributes = entitlement.attributes || [];

  console.log();
  console.log("Imported entitlement");
  console.log(`  Entitlement ID: ${valueOrUnknown(entitlement.id)}`);
  console.log(`  Product ID:     ${valueOrUnknown(product.id || entitlement.productId)}`);
  console.log(`  Product name:   ${valueOrUnknown(product.name || entitlement.productName)}`);
  console.log(`  Offering:       ${valueOrUnknown(entitlement.offeringName)}`);
  console.log(`  Activation codes: ${activationCodes.length}`);
  if (activationCodes.length > 0) {
    console.log(`  First activation code: ${activationCodes[0]}`);
  }
  console.log(`  Features:       ${features.length}`);
  console.log(`  Attributes:     ${attributes.length}`);
}

function promptRequired(label) {
  return prompt(label).then((value) => {
    if (value) {
      return value;
    }

    console.log(`${label} is required.`);
    return promptRequired(label);
  });
}

function promptStoredRequired(label, key) {
  return promptWithDefault(label, storedEnv[key]).then((value) => {
    if (value) {
      return value;
    }

    console.log(`${label} is required.`);
    return promptStoredRequired(label, key);
  });
}

function promptSecretRequired(label) {
  return promptSecret(label).then((value) => {
    if (value) {
      return value;
    }

    console.log(`${label} is required.`);
    return promptSecretRequired(label);
  });
}

function promptWithDefault(label, defaultValue) {
  if (pipedAnswers) {
    process.stdout.write(`${label}${defaultValue ? ` [${defaultValue}]` : ""}: `);
    const answer = (pipedAnswers.shift() || "").trim();
    return Promise.resolve(answer || defaultValue || "");
  }

  const interfaceInstance = getReadline();
  const suffix = defaultValue ? ` [${defaultValue}]` : "";

  return new Promise((resolve) => {
    interfaceInstance.question(`${label}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

function prompt(label) {
  if (pipedAnswers) {
    process.stdout.write(`${label}: `);
    return Promise.resolve((pipedAnswers.shift() || "").trim());
  }

  const interfaceInstance = getReadline();

  return new Promise((resolve) => {
    interfaceInstance.question(`${label}: `, (answer) => {
      resolve(answer.trim());
    });
  });
}

function promptSecret(label) {
  if (pipedAnswers) {
    process.stdout.write(`${label}: `);
    console.log();
    return Promise.resolve((pipedAnswers.shift() || "").trim());
  }

  const interfaceInstance = getReadline();

  return new Promise((resolve) => {
    interfaceInstance.question(`${label}: `, (answer) => {
      muteReadlineOutput = false;
      console.log();
      resolve(answer.trim());
    });
    muteReadlineOutput = true;
  });
}

function getReadline() {
  if (rl) {
    return rl;
  }

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  originalWriteToOutput = rl._writeToOutput;
  rl._writeToOutput = function writeToOutput(text) {
    if (!muteReadlineOutput) {
      originalWriteToOutput.call(rl, text);
    }
  };

  return rl;
}

function closeReadline() {
  if (rl) {
    rl.close();
  }
}

function normalizeTokenUrl(value) {
  const trimmed = trimTrailingSlash(value);
  if (trimmed.endsWith("/protocol/openid-connect/token")) {
    return trimmed;
  }

  return `${trimmed}/protocol/openid-connect/token`;
}

function trimTrailingSlash(value) {
  return value.endsWith("/") ? value.slice(0, -1) : value;
}

function isHttpsUrl(value) {
  return new URL(value).protocol === "https:";
}

function maskToken(token) {
  return token.length <= 30 ? token : `${token.slice(0, 30)}...`;
}

function requireToken(response, description) {
  if (!response.token) {
    throw new Error(`${description} did not include a token.`);
  }

  return response.token;
}

function valueOrUnknown(value) {
  return value === undefined || value === null || value === "" ? "<unknown>" : value;
}

function parseJson(value) {
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function readEnvFile(path) {
  if (!fs.existsSync(path)) {
    return {};
  }

  const result = {};
  const content = fs.readFileSync(path, "utf8");
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) {
      continue;
    }

    const separatorIndex = trimmed.indexOf("=");
    const key = trimmed.slice(0, separatorIndex).trim();
    const value = trimmed.slice(separatorIndex + 1).trim();
    result[key] = unquoteEnvValue(value);
  }

  return result;
}

function writeEnvFile(path, values) {
  const lines = [
    "# Local License Server walkthrough settings",
    "# Secrets and passwords are intentionally not stored.",
  ];

  for (const key of Object.values(ENV_KEYS)) {
    const value = values[key] || storedEnv[key];
    if (value) {
      lines.push(`${key}=${quoteEnvValue(value)}`);
    }
  }

  fs.writeFileSync(path, `${lines.join("\n")}\n`, "utf8");
}

function quoteEnvValue(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function unquoteEnvValue(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value
      .slice(1, -1)
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, "\\");
  }

  return value;
}

main().catch((error) => {
  closeReadline();

  if (error instanceof ApiError) {
    console.error(`HTTP ${error.statusCode} from ${error.method} ${error.url}`);
    if (error.body) {
      console.error(error.body);
    }
  } else {
    console.error(`Error: ${error.message}`);
  }

  process.exit(1);
});
